// Reusable UI pieces: trading view, chart, challenge solver, profile card, toasts.

import { TRADE_FEE } from '../../shared/catalog.js';
import type { Challenge, PublicProfile } from '../../shared/types.js';
import { api } from '../api.js';
import { audio } from '../audio/audio.js';
import { act } from '../net/client.js';
import { fmt, portfolioValue, store } from '../state.js';
import { SIM, add, badge, btn, h, input, select, useData, invalidate } from './dom.js';

export function toast(text: string, kind = 'info') {
  const wrap = document.getElementById('toasts');
  if (!wrap) return;
  const t = h('div.toast.' + kind, text);
  wrap.prepend(t);
  if (wrap.children.length > 5) wrap.lastElementChild?.remove();
  setTimeout(() => t.classList.add('out'), kind === 'warn' ? 6500 : 4500);
  setTimeout(() => t.remove(), kind === 'warn' ? 7000 : 5000);
  audio.sfx(kind === 'money' || kind === 'trade' ? 'cash' : kind === 'level' || kind === 'achievement' ? 'level' : kind === 'warn' ? 'error' : 'notify');
}

export async function run<T>(p: Promise<T>, ok?: string): Promise<T | undefined> {
  try {
    const r = await p;
    if (ok) toast(ok, 'ok');
    return r;
  } catch (e) {
    toast((e as Error).message, 'warn');
    return undefined;
  }
}

export function sparkline(vals: number[], w = 80, hgt = 24) {
  const c = h('canvas', { width: w * 2, height: hgt * 2, style: { width: w + 'px', height: hgt + 'px' } }) as HTMLCanvasElement;
  const x = c.getContext('2d')!;
  if (vals.length > 1) {
    const mn = Math.min(...vals), mx = Math.max(...vals), r = mx - mn || 1;
    x.strokeStyle = vals[vals.length - 1] >= vals[0] ? '#38f2a5' : '#ff5a6e'; x.lineWidth = 3;
    x.beginPath();
    vals.forEach((v, i) => { const px = (i / (vals.length - 1)) * w * 2, py = hgt * 2 - ((v - mn) / r) * (hgt * 2 - 4) - 2; i ? x.lineTo(px, py) : x.moveTo(px, py); });
    x.stroke();
  }
  return c;
}

export function candleChart(sym: string, w: number, hgt: number, rerender: () => void) {
  const c = h('canvas.chart', { width: w * 2, height: hgt * 2, style: { width: '100%', height: hgt + 'px' } }) as HTMLCanvasElement;
  const { data } = useData<{ t: number; o: number; h: number; l: number; c: number }[]>('hist:' + sym, () => act('market.history', { sym }), 15000, rerender);
  const x = c.getContext('2d')!;
  x.fillStyle = '#070a12'; x.fillRect(0, 0, c.width, c.height);
  const candles = (data ?? []).slice(-80);
  const live = store.prices[sym];
  if (candles.length && live) { const last = candles[candles.length - 1]; candles[candles.length - 1] = { ...last, c: live, h: Math.max(last.h, live), l: Math.min(last.l, live) }; }
  if (candles.length > 1) {
    const mn = Math.min(...candles.map((k) => k.l)), mx = Math.max(...candles.map((k) => k.h));
    const r = mx - mn || mx * 0.01;
    const Y = (v: number) => c.height - 20 - ((v - mn) / r) * (c.height - 40);
    const cw = c.width / candles.length;
    x.strokeStyle = 'rgba(255,255,255,0.05)';
    for (let i = 0; i < 5; i++) { x.beginPath(); x.moveTo(0, 20 + i * (c.height - 40) / 4); x.lineTo(c.width, 20 + i * (c.height - 40) / 4); x.stroke(); }
    candles.forEach((k, i) => {
      const up = k.c >= k.o;
      x.strokeStyle = x.fillStyle = up ? '#38f2a5' : '#ff5a6e';
      const cx = i * cw + cw / 2;
      x.beginPath(); x.moveTo(cx, Y(k.h)); x.lineTo(cx, Y(k.l)); x.lineWidth = 2; x.stroke();
      const top = Y(Math.max(k.o, k.c)), bot = Y(Math.min(k.o, k.c));
      x.fillRect(i * cw + cw * 0.18, top, cw * 0.64, Math.max(2, bot - top));
    });
    x.fillStyle = '#9aa3ad'; x.font = '20px Consolas'; x.textAlign = 'right';
    x.fillText(fmt.price(mx), c.width - 6, 22); x.fillText(fmt.price(mn), c.width - 6, c.height - 4);
  } else { x.fillStyle = '#556'; x.font = '22px Consolas'; x.fillText('Loading…', 20, 40); }
  x.fillStyle = '#ffb03f'; x.font = 'bold 20px Consolas'; x.textAlign = 'left'; x.fillText('SIMULATED · 15s candles', 10, 22);
  return c;
}

let tradeSym = 'SGLD';
let tradeSide: 'buy' | 'sell' = 'buy';
let tradeType: 'market' | 'limit' | 'stop' | 'take_profit' = 'market';
let tradeAmt = '';
let tradeAmtMode: 'usd' | 'qty' = 'usd';
let tradePrice = '';

export function tradingView(el: HTMLElement, rerender: () => void, compact = false) {
  const me = store.me!;
  const toks = store.tokens;
  const tok = toks.find((t) => t.sym === tradeSym) ?? toks[0];
  if (!tok) { add(el, h('p', 'Loading market…')); return; }
  tradeSym = tok.sym;
  const p = store.prices[tok.sym] ?? tok.price;
  const ch = ((p - tok.open24) / tok.open24) * 100;
  add(el, h('div.banner.sim', '⚠ SIMULATED MARKET — prices are generated by the game engine, not live market data. Trades use simulated currency.'));
  const list = h('div.toklist.scroll', toks.map((t) => {
    const tp = store.prices[t.sym] ?? t.price;
    const tc = ((tp - t.open24) / t.open24) * 100;
    return h('div.tok' + (t.sym === tok.sym ? '.sel' : ''), { onclick: () => { tradeSym = t.sym; rerender(); } },
      h('div', h('b', t.sym), h('small', ' ' + t.name + (t.launchedBy ? ` · by @${t.launchedBy}` : ''))),
      sparkline(store.priceHistory[t.sym] ?? [], 60, 18),
      h('div.r', h('div', fmt.price(tp)), h('small.' + (tc >= 0 ? 'up' : 'dn'), fmt.pct(tc))),
      h('span.star' + (me.watchlist.includes(t.sym) ? '.on' : ''), { onclick: (e: Event) => { e.stopPropagation(); run(act('market.watch', { sym: t.sym, on: !me.watchlist.includes(t.sym) })); } }, '★'));
  }));
  const held = me.holdings[tok.sym] ?? 0;
  const basis = me.costBasis[tok.sym] ?? 0;
  const upnl = held * p - basis;
  const amt = input({ type: 'number', min: '0', step: 'any', placeholder: tradeAmtMode === 'usd' ? 'Amount in $' : `Quantity of ${tok.sym}`, value: tradeAmt, oninput: (e: Event) => { tradeAmt = (e.target as HTMLInputElement).value; } });
  const pr = input({ type: 'number', min: '0', step: 'any', placeholder: 'Trigger / limit price', value: tradePrice, oninput: (e: Event) => { tradePrice = (e.target as HTMLInputElement).value; } });
  const est = () => {
    const a = Number(tradeAmt) || 0;
    const px = tradeType === 'market' ? p : Number(tradePrice) || p;
    const qty = tradeAmtMode === 'usd' ? a / px : a;
    return { qty, usd: qty * px, fee: qty * px * TRADE_FEE };
  };
  const e = est();
  const form = h('div.orderform',
    h('div.seg', btn('Buy', () => { tradeSide = 'buy'; if (tradeType === 'stop' || tradeType === 'take_profit') tradeType = 'market'; rerender(); }, tradeSide === 'buy' ? 'on buy' : ''), btn('Sell', () => { tradeSide = 'sell'; rerender(); }, tradeSide === 'sell' ? 'on sell' : '')),
    h('div.seg.small', (['market', 'limit', 'stop', 'take_profit'] as const).filter((t) => tradeSide === 'sell' || t === 'market' || t === 'limit').map((t) => btn(t === 'take_profit' ? 'Take-profit' : t === 'stop' ? 'Stop-loss' : t[0].toUpperCase() + t.slice(1), () => { tradeType = t; rerender(); }, tradeType === t ? 'on' : ''))),
    h('div.row', amt, select([['usd', '$'], ['qty', tok.sym]], tradeAmtMode, (v) => { tradeAmtMode = v as 'usd' | 'qty'; rerender(); })),
    tradeType !== 'market' ? pr : null,
    h('div.quick', [25, 50, 100].map((pc) => btn(pc + '%', () => {
      if (tradeSide === 'buy') { tradeAmtMode = 'usd'; tradeAmt = String(Math.floor(me.cash * pc) / 100 / (1 + TRADE_FEE)); }
      else { tradeAmtMode = 'qty'; tradeAmt = String((held * pc) / 100); }
      rerender();
    }, 'ghost'))),
    h('small.muted', `≈ ${fmt.qty(e.qty)} ${tok.sym} · ${fmt.usd(e.usd)} · fee ${fmt.usd(e.fee)} (0.1%)${tradeType === 'market' ? ' · market orders may slip' : ''}`),
    btn(`${tradeSide === 'buy' ? 'Buy' : 'Sell'} ${tok.sym}`, async () => {
      const a = Number(tradeAmt);
      if (!(a > 0)) { toast('Enter an amount', 'warn'); return; }
      const args: Record<string, unknown> = { sym: tok.sym, side: tradeSide, type: tradeType };
      if (tradeAmtMode === 'usd') args.usd = a; else args.qty = a;
      if (tradeType !== 'market') { args.price = Number(tradePrice); if (tradeAmtMode === 'usd') { args.qty = a / Number(tradePrice); delete args.usd; } }
      const r = await run(act('market.order', args));
      if (r) { toast(tradeType === 'market' ? `Filled: ${tradeSide} ${tok.sym}` : `Order placed: ${tradeType.replace('_', '-')} ${tok.sym}`, 'trade'); tradeAmt = ''; rerender(); }
    }, 'primary ' + tradeSide));
  const orders = me.orders.filter((o) => compact ? o.sym === tok.sym : true);
  add(el, h('div.trade' + (compact ? '.compact' : ''),
    h('div.trade-left', list),
    h('div.trade-main',
      h('div.trade-head', h('h3', tok.sym, ' ', h('small', tok.name)), h('div', h('b.big', fmt.price(p)), ' ', h('span.' + (ch >= 0 ? 'up' : 'dn'), fmt.pct(ch) + ' 24h')), SIM()),
      candleChart(tok.sym, 600, compact ? 150 : 220, rerender),
      h('div.cols',
        form,
        h('div.pos',
          h('h4', 'Your position'),
          h('div', `Holding: ${fmt.qty(held)} ${tok.sym}`), h('div', `Value: ${fmt.usd(held * p)}`),
          held > 0 ? h('div', 'Unrealized P&L: ', h('span.' + (upnl >= 0 ? 'up' : 'dn'), fmt.usd(upnl))) : null,
          h('div.muted', `Cash: ${fmt.usd(me.cash)} · Portfolio: ${fmt.usd(portfolioValue())}`),
          h('h4', 'Open orders'),
          orders.length ? orders.map((o) => h('div.order', `${o.type.replace('_', '-')} ${o.side} ${fmt.qty(o.qty)} ${o.sym} @ ${fmt.price(o.price ?? 0)}`, btn('Cancel', () => run(act('market.cancel', { id: o.id }), 'Order cancelled'), 'ghost small'))) : h('div.muted', 'None'),
        )),
      h('h4', 'Recent fills'),
      h('div.fills.scroll', me.fills.slice(0, 15).map((f) => h('div.fill', h('span.' + (f.side === 'buy' ? 'up' : 'dn'), f.side.toUpperCase()), ` ${fmt.qty(f.qty)} ${f.sym} @ ${fmt.price(f.price)}`, f.pnl !== undefined ? h('span.' + (f.pnl >= 0 ? 'up' : 'dn'), ` P&L ${fmt.usd(f.pnl)}`) : '', h('small.muted', ' ' + fmt.ago(f.ts))))),
    )));
}

export function challengeView(el: HTMLElement, c: Challenge, submit: (answer: number[]) => Promise<{ correct: boolean; answer: number[]; pay?: number; xp?: number; score?: number } | undefined>, onDone: () => void) {
  const chosen = new Set<number>();
  let result: { correct: boolean; answer: number[]; pay?: number; xp?: number; score?: number } | null = null;
  const draw = () => {
    el.innerHTML = '';
    add(el, h('div.challenge',
      h('p.prompt', c.prompt),
      c.code ? h('pre.code', c.code) : null,
      c.multi ? h('small.muted', 'Select all that apply') : null,
      h('div.options', c.options.map((o, i) => h('button.opt' + (chosen.has(i) ? '.sel' : '') + (result ? (result.answer.includes(i) ? '.right' : chosen.has(i) ? '.wrong' : '') : ''), {
        onclick: () => { if (result) return; if (!c.multi) chosen.clear(); chosen.has(i) ? chosen.delete(i) : chosen.add(i); draw(); },
      }, o))),
      result
        ? h('div.result.' + (result.correct ? 'ok' : 'bad'), result.correct ? '✔ Correct!' : '✘ Not quite.', result.pay !== undefined ? ` Paid ${fmt.usd(result.pay)} (simulated).` : '', result.xp ? ` +${result.xp} XP` : '', result.score !== undefined ? ` Score: ${result.score}` : '', h('div', btn('Done', onDone, 'primary')))
        : btn('Submit', async () => { if (!chosen.size) { toast('Pick an answer', 'warn'); return; } const r = await run(submit([...chosen])); if (r) { result = r; draw(); } }, 'primary'),
    ));
  };
  draw();
}

export function profileCard(p: PublicProfile, rerender: () => void) {
  const me = store.me!;
  const isMe = p.username === me.username;
  return h('div.profile-card',
    h('div.avatar', { style: { background: p.look.colors.top ?? '#334' } }, p.username[0].toUpperCase()),
    h('h3', '@' + p.username, ' ', p.online ? badge('online', 'ok') : badge('offline')),
    h('div.muted', `${p.career} · Level ${p.level} · Reputation ${p.reputation}`),
    h('div.stats', h('span', h('b', p.followers), ' followers'), h('span', h('b', p.following), ' following'), p.driverRating ? h('span', '★ ', h('b', p.driverRating), ' driver') : null),
    p.netWorth !== undefined ? h('div', 'Net worth: ', fmt.usd(p.netWorth), ' ', SIM()) : h('div.muted', 'Portfolio: private'),
    p.balance !== undefined ? h('div', 'Wallet: ', fmt.usd(p.balance), ' ', SIM()) : null,
    p.home ? h('div', '🏠 ', p.home) : null,
    p.vehicles?.length ? h('div', '🚗 ', p.vehicles.join(', ')) : null,
    p.projects.length ? h('div', '🚀 ', p.projects.map((x) => x.name).join(', ')) : null,
    h('div.achv', p.achievements.slice(0, 12).map((a) => badge(a))),
    isMe ? null : h('div.actions',
      btn(p.youFollow ? 'Unfollow' : 'Follow', () => run(act('social.follow', { username: p.username, on: !p.youFollow })).then(() => { invalidate('prof:'); rerender(); })),
      p.isFriend ? btn('Unfriend', () => run(act('friends.remove', { username: p.username }), 'Removed').then(() => { invalidate('prof:'); rerender(); }), 'ghost') : btn('Add friend', () => run(act('friends.request', { username: p.username }), 'Friend request sent')),
      btn('Message', () => api.panel('phone:messages', { ch: 'dm:' + p.username })),
      btn('Pay', () => api.panel('phone:wallet', { to: p.username })),
      btn('Invite home', () => run(act('home.invite', { username: p.username }), `Invited @${p.username} to your home`)),
      btn(me.blocked.includes(p.username) ? 'Unblock' : 'Block', () => run(act('social.block', { username: p.username, on: !me.blocked.includes(p.username) }), 'Updated'), 'ghost'),
      btn('Report', async () => { const reason = prompt('Why are you reporting @' + p.username + '?'); if (reason) await run(act('social.report', { username: p.username, reason }), 'Report submitted to moderation'); }, 'ghost danger'),
    ));
}
