// PBR texture sets (generated by tools/gen_textures.py) and world-aligned
// surface materials. World-aligned UVs mean merged/batched geometry needs no
// UV work, and a low-frequency "macro" variation hides texture repetition.

import * as THREE from 'three';

const loader = new THREE.TextureLoader();
const cache = new Map<string, THREE.Texture>();
let aniso = 8;
export function setPbrAnisotropy(n: number) { aniso = n; }

function tex(file: string, srgb: boolean) {
  let t = cache.get(file);
  if (!t) {
    t = loader.load((import.meta.env.BASE_URL ?? '/') + 'assets/tex/' + file);
    t.wrapS = t.wrapT = THREE.RepeatWrapping;
    t.colorSpace = srgb ? THREE.SRGBColorSpace : THREE.NoColorSpace;
    t.anisotropy = aniso;
    cache.set(file, t);
  }
  return t;
}

export interface PbrSet { map: THREE.Texture; normalMap: THREE.Texture; orm: THREE.Texture }

/** Texture set tiled every `tile` metres (for geometry whose uv is in metres). */
export function pbrSet(name: string, tile: number): PbrSet {
  const mk = (t: THREE.Texture) => { const c = t.clone(); c.repeat.set(1 / tile, 1 / tile); c.needsUpdate = true; return c; };
  return { map: mk(tex(name + '_albedo.jpg', true)), normalMap: mk(tex(name + '_normal.jpg', false)), orm: mk(tex(name + '_orm.jpg', false)) };
}

export interface SurfaceOpts {
  tile: number;
  /** 'ground' maps world XZ; 'wall' picks the dominant vertical axis; 'uv' keeps mesh UVs (in metres). */
  mode?: 'ground' | 'wall' | 'uv';
  color?: THREE.ColorRepresentation;
  roughness?: number;
  normalScale?: number;
  macro?: number;         // strength of large-scale variation
  wet?: boolean;          // allow the shared wetness uniform to darken / gloss it
}

/** Rain wetness 0..1 shared by every ground material. */
export const surfaceUniforms = { uWet: { value: 0 } };

export function surfaceMaterial(name: string, o: SurfaceOpts) {
  const set = pbrSet(name, 1);
  const m = new THREE.MeshStandardMaterial({
    map: set.map, normalMap: set.normalMap, roughnessMap: set.orm, aoMap: set.orm,
    color: o.color ?? 0xffffff, roughness: o.roughness ?? 1, metalness: 0,
    normalScale: new THREE.Vector2(o.normalScale ?? 1, o.normalScale ?? 1),
  });
  const mode = o.mode ?? 'ground';
  const macro = o.macro ?? 0.25;
  m.onBeforeCompile = (sh) => {
    Object.assign(sh.uniforms, surfaceUniforms, { uTile: { value: o.tile } });
    sh.vertexShader = sh.vertexShader
      .replace('#include <common>', '#include <common>\nuniform float uTile; varying vec3 vSWPos;')
      .replace('#include <uv_vertex>', `#include <uv_vertex>
        {
          vec3 wp = (modelMatrix * vec4(position, 1.0)).xyz;
          vec3 wn = abs(normalize(mat3(modelMatrix) * normal));
          vec2 suv = ${mode === 'ground' ? 'wp.xz' : mode === 'wall' ? '(wn.y > 0.7 ? wp.xz : wn.x > wn.z ? vec2(wp.z, wp.y) : vec2(wp.x, wp.y))' : 'uv'} / uTile;
          vSWPos = wp;
          #ifdef USE_MAP
          vMapUv = suv;
          #endif
          #ifdef USE_NORMALMAP
          vNormalMapUv = suv;
          #endif
          #ifdef USE_ROUGHNESSMAP
          vRoughnessMapUv = suv;
          #endif
          #ifdef USE_AOMAP
          vAoMapUv = suv;
          #endif
        }`);
    sh.fragmentShader = sh.fragmentShader
      .replace('#include <common>', `#include <common>
        uniform float uWet; varying vec3 vSWPos;
        float sh2(vec2 p) { return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453); }
        float snoise(vec2 p) { vec2 i = floor(p), f = fract(p); f = f * f * (3.0 - 2.0 * f);
          return mix(mix(sh2(i), sh2(i + vec2(1, 0)), f.x), mix(sh2(i + vec2(0, 1)), sh2(i + vec2(1, 1)), f.x), f.y); }`)
      .replace('#include <map_fragment>', `#include <map_fragment>
        float sMacro = snoise(vSWPos.xz * 0.045) * 0.6 + snoise(vSWPos.xz * 0.19 + 7.0) * 0.4;
        diffuseColor.rgb *= 1.0 - ${macro.toFixed(3)} * 0.5 + sMacro * ${macro.toFixed(3)};
        ${o.wet ? 'float sWet = uWet * smoothstep(0.35, 0.75, snoise(vSWPos.xz * 0.12) * 0.7 + 0.3);\n        diffuseColor.rgb *= 1.0 - sWet * 0.45;' : 'float sWet = 0.0;'}`)
      .replace('#include <roughnessmap_fragment>', `#include <roughnessmap_fragment>
        roughnessFactor = mix(roughnessFactor, 0.08, sWet);`);
  };
  m.customProgramCacheKey = () => `surf_${name}_${mode}_${o.tile}_${macro}_${!!o.wet}`;
  return m;
}

/** Weathers painted road markings: chipped edges, faded patches, tyre grime. */
export function wearPaint(m: THREE.MeshStandardMaterial, strength = 1) {
  m.onBeforeCompile = (sh) => {
    sh.vertexShader = sh.vertexShader
      .replace('#include <common>', '#include <common>\nvarying vec3 vPWPos;')
      .replace('#include <begin_vertex>', '#include <begin_vertex>\nvPWPos = (modelMatrix * vec4(position, 1.0)).xyz;');
    sh.fragmentShader = sh.fragmentShader
      .replace('#include <common>', `#include <common>
        varying vec3 vPWPos;
        float ph(vec2 p) { return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453); }
        float pn(vec2 p) { vec2 i = floor(p), f = fract(p); f = f * f * (3.0 - 2.0 * f);
          return mix(mix(ph(i), ph(i + vec2(1, 0)), f.x), mix(ph(i + vec2(0, 1)), ph(i + vec2(1, 1)), f.x), f.y); }`)
      .replace('#include <map_fragment>', `#include <map_fragment>
        {
          float chip = pn(vPWPos.xz * 9.0) * 0.55 + pn(vPWPos.xz * 37.0) * 0.45;
          float fade = pn(vPWPos.xz * 0.35) * 0.6 + pn(vPWPos.xz * 1.7) * 0.4;
          float keep = smoothstep(0.1, 0.3, chip - (fade - 0.5) * 0.45 * ${strength.toFixed(2)});
          diffuseColor.a *= keep * mix(0.55, 0.95, fade);
          diffuseColor.rgb *= mix(0.72, 0.95, pn(vPWPos.xz * 3.0));
        }`);
  };
  m.customProgramCacheKey = () => 'wornpaint' + strength;
  return m;
}

/** Street decals atlas: 0 manhole, 1 drain grate, 2 oil stain, 3 cracks. */
export function decalMaterial() {
  const base = (import.meta.env.BASE_URL ?? '/') + 'assets/tex/';
  const map = loader.load(base + 'decals_albedo.png');
  map.colorSpace = THREE.SRGBColorSpace; map.anisotropy = aniso;
  const normalMap = loader.load(base + 'decals_normal.jpg');
  normalMap.anisotropy = aniso;
  return new THREE.MeshStandardMaterial({ map, normalMap, transparent: true, depthWrite: false, roughness: 0.55, metalness: 0.25, polygonOffset: true, polygonOffsetFactor: -1, polygonOffsetUnits: -1 });
}

/** Ground quad (lying flat) showing one tile of a horizontal atlas with `tiles` cells. */
export function atlasQuad(w: number, h: number, tile: number, tiles = 4) {
  const g = new THREE.PlaneGeometry(w, h);
  const uv = g.attributes.uv as THREE.BufferAttribute;
  for (let i = 0; i < uv.count; i++) uv.setX(i, (tile + uv.getX(i)) / tiles);
  g.rotateX(-Math.PI / 2);
  return g;
}

const surfCache = new Map<string, THREE.MeshStandardMaterial>();
/** Cached surfaceMaterial (identical name + options share one material). */
export function surf(name: string, o: SurfaceOpts) {
  const key = name + JSON.stringify(o);
  let m = surfCache.get(key);
  if (!m) { m = surfaceMaterial(name, o); surfCache.set(key, m); }
  return m;
}
